Repository lschaeffer313/domaine-nc-mobile, pull requests merged in 2022-11, with the labels that each got.

#38 Ajout des contributeurs
  CONTRIBUTORS.md
Labels: documentation, communication, RUN

#40 Ajout de Ronny
  CONTRIBUTORS.md
Labels: documentation, RUN, quickfix

#55 32 modifier le readme afin dexpliquer en quoi consiste ce projet
  README.md
Labels: documentation, communication, RUN, quickfix

#58 Ajout Matthieu MAOUDJ
  CONTRIBUTORS.md
Labels: documentation, RUN, quickfix

#60 doc(README) : mauvais layout md
  README.md
Labels: documentation, RUN, quickfix

#61 doc(contribuer) : section dédiée
  README.md
Labels: documentation, enhancement, BUILD, communication, quickfix

#63 🚨 Impossible de lire Serveur DNS dans certains cas
  lib/page/domaine_detail_page.dart
Labels: bug, RUN, quickfix
