Repository lschaeffer313/domaine-nc-mobile, pull requests merged in 2022-12, with the labels that each got.

#67 doc(contributors) : Ajout de Sabrina
  CONTRIBUTORS.md
Labels: documentation, communication, RUN, quickfix

#65 Ajout badge sur le README
  .github/workflows/deploy_to_alpha.yml
  README.md
Labels: documentation, RUN

#75 doc(sysamadine) : Les noms de domaine en Nouvelle-Calédonie ?
  README.md
Labels: documentation, enhancement, RUN, quickfix

#77 Ajout Discord
  README.md
Labels: documentation, RUN, quickfix

#73 doc(better desc)
  README.md
Labels: documentation, enhancement, RUN, quickfix

#86 Ajout d'une page d'information
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/page/about_page.dart
  lib/routes/search_route.dart
  lib/theme/dark_theme.dart
  lib/theme/light_theme.dart
  lib/widget/search_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#93 :bug: Icône du téléphone illisible
  lib/theme/dark_theme.dart
Labels: quickfix, dart

#98 Ajout short uri au badge
  README.md
Labels: documentation, communication, RUN, quickfix
