Repository lschaeffer313/domaine-nc-mobile, pull requests merged in 2023-07, with the labels that each got.

#179 178 bug accorder pluriel sur serveurs dns
  lib/page/domaine_detail_page.dart
Labels: bug, RUN, quickfix

#180 :bug: Accorde au pluriel serveur en fonction du nombre de serveur
  lib/page/domaine_detail_page.dart
Labels: enhancement, RUN, dart

#181 Mise à jour main
  lib/page/domaine_detail_page.dart
  pubspec.lock
  pubspec.yaml
Labels: BUILD
