Repository lschaeffer313/domaine-nc-mobile, pull requests merged in 2023-02, with the labels that each got.

#140 💡 doc(README) : (Mais...) Pourquoi cette appli :⁉️ 🤔
  README.md
Labels: documentation, BUILD, communication, quickfix

#146 fix(writing): Implement epicene writing in CONTRIBUTEURS.md
  CONTRIBUTORS.md
Labels: documentation, communication, RUN, quickfix

#149 fix(wording): Fix typos/unconsistent wording in ternary operators
  lib/page/domaine_detail_page.dart
Labels: bug, RUN

#152 Mise à jour main
  CONTRIBUTORS.md
  README.md
  lib/page/domaine_detail_page.dart
Labels: BUILD

#153 doc(README) : Article Testeum
  README.md
Labels: documentation, communication, RUN, quickfix

#155 Ajout lint pour le code dart
  .github/workflows/deploy_to_prod.yml
  .github/workflows/on_pull_push_develop.yml
  analysis_options.yaml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/assets/constants.dart
  lib/model/domaine_info.dart
  lib/model/domaine_search_result.dart
  lib/page/domaine_detail_page.dart
  lib/routes/search_route.dart
  lib/service/domaine_service.dart
  pubspec.lock
Labels: ci, github_actions, dart

#156 doc(README) : AJout contributeur designer du logo cool
  CONTRIBUTORS.md
Labels: communication, RUN

#157 Ajout du nouveau logo de l'application
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  lib/assets/icon/icon.png
Labels: UX

#160 Génération des icône pour les différentes tailles de device
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
Labels: enhancement

#164 :memo: doc(README) : lien post fastlane
  README.md
Labels: documentation, RUN, quickfix
