Repository lschaeffer313/domaine-nc-mobile, pull requests merged in 2023-01, with the labels that each got.

#104 :bug: Enlever octocat emoji
  CONTRIBUTORS.md
Labels: bug, documentation, RUN, quickfix

#112 Mise à jour main
  CONTRIBUTORS.md
  README.md
Labels: documentation

#117 :sponge: doc(contributeurs) : contributeurs vraiment actifs
  CONTRIBUTORS.md
Labels: documentation, RUN, quickfix

#125 🩹 Changement effectué suite aux retour de la campagne Testeum
  lib/page/domaine_detail_page.dart
  lib/page/info_search_page.dart
  lib/page/search_domaine_page.dart
  lib/utils/error_utils.dart
  lib/widget/search_bar.dart
Labels: bug, dart, UX

#129 doc(description projet) : meilleure descritpion du projet
  pubspec.yaml
Labels: documentation, RUN, quickfix

#136 Mise à jour dépendance, version de dart utilisé et changement du sdk utilisé sur "Stable" pour la CI
  .github/workflows/deploy_to_prod.yml
  pubspec.lock
  pubspec.yaml
Labels: BUILD, ci, dart

#137 Changement de place du titre sur la page d'un domaine
  lib/page/domaine_detail_page.dart
  lib/widget/domain_specific_info.dart
Labels: BUILD, quickfix, dart, UX
